version: '3.7'

services:
    app:
      build: .
      container_name: app
      ports:
        - 8001:8000/tcp
      command: 0.0.0.0:8000
      networks:
        app-net:
          aliases:
              - "app"

networks:
  app-net:
    driver: bridge