# Generated by Django 3.1.1 on 2020-09-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Новое меню',
                'verbose_name_plural': 'Новое меню',
            },
        ),
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('tag', models.CharField(max_length=100, verbose_name='Теги')),
                ('content', models.TextField(verbose_name='Содержание статьи')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новый пост',
                'verbose_name_plural': 'Новые посты',
            },
        ),
    ]
