# Generated by Django 3.1.1 on 2020-09-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AddField(
            model_name='newpost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
