# Generated by Django 3.1.1 on 2020-09-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200928_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='Тег'),
        ),
    ]
