# Generated by Django 3.1.1 on 2020-09-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
