# Generated by Django 3.1.1 on 2020-09-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profilephoto_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilephoto',
            name='title',
        ),
    ]
