# Generated by Django 3.1.1 on 2020-09-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_profilephoto_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
    ]
