# Generated by Django 3.1.1 on 2020-09-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profilephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
    ]
