# Generated by Django 3.1.1 on 2020-09-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Дополнительная инфа', 'verbose_name_plural': 'Дополнительная инфа'},
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile', verbose_name='Фото профиля'),
        ),
    ]
